name: Configure SSH Cpolar Server

permissions:
  contents: write  # 允许写入仓库内容（例如推送标签）
  actions: write   # 允许触发其他工作流

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify root password (local)
        run: |
          echo "root:Wex12356" | sudo chpasswd

      - name: Allow root login (local)
        run: |
          sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?ClientAliveInterval.*/ClientAliveInterval 60/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?ClientAliveCountMax.*/ClientAliveCountMax 720/' /etc/ssh/sshd_config
          
          sudo systemctl restart ssh

      - name: Install and configure cpolar (local)
        run: |
         sudo apt install wget
         sudo wget https://www.cpolar.com/static/downloads/releases/3.3.18/cpolar-stable-linux-amd64.zip
         sudo apt install unzip -y
         sudo unzip cpolar-stable-linux-amd64.zip
         sudo chmod 777 cpolar
         sudo cpolar authtoken NWVmNGFhOTgtYjIwMC00N2M5LTk4NmMtMjVjZmU1OTk5MTYw
         sudo bash cpolar tcp 22
          
