name: Configure SSH FRP Server

permissions:
  contents: write  # 允许写入仓库内容（例如推送标签）
  actions: write   # 允许触发其他工作流

on:
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      root_password:
        description: 'New root password'
        required: true
        type: string
      frp_server_addr:
        description: 'FRP server address'
        required: true
        type: string
      frp_server_port:
        description: 'FRP server port'
        required: true
        type: string

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Modify root password (local)
      run: |
        echo "root:${{ inputs.root_password }}" | sudo chpasswd

    - name: Allow root login (local)
      run: |
        sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo systemctl restart sshd

    - name: Install and configure frpc (local)
      run: |
        wget https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_linux_amd64.tar.gz
        tar -xzf frp_0.51.3_linux_amd64.tar.gz
        sudo mv frp_0.51.3_linux_amd64/frpc /usr/local/bin/frpc
        sudo chmod +x /usr/local/bin/frpc
        echo '[common]
        server_addr = ${{ inputs.frp_server_addr }}
        server_port = ${{ inputs.frp_server_port }}
        [ssh]
        type = tcp
        local_ip = 127.0.0.1
        local_port = 22
        remote_port = 6000' | sudo tee /etc/frpc.ini
        sudo frpc -c /etc/frpc.ini &
